services:
  LINKDROP:
    image: danielszabo99/LINKDROP:latest
    restart: always
    ports:
     - "${LINKDROP_PORT}:8080"
    volumes:
     - ./LINKDROP-data:/app/LINKDROP_data
    environment:
      LINKDROP_BASIC_AUTH_USERNAME: ${LINKDROP_BASIC_AUTH_USERNAME}
      LINKDROP_BASIC_AUTH_PASSWORD: ${LINKDROP_BASIC_AUTH_PASSWORD}
      LINKDROP_ADMIN_USERNAME: ${LINKDROP_ADMIN_USERNAME}
      LINKDROP_ADMIN_PASSWORD: ${LINKDROP_ADMIN_PASSWORD}
      LINKDROP_EDITABLE: ${LINKDROP_EDITABLE}
      LINKDROP_FOOTER_TEXT: ${LINKDROP_FOOTER_TEXT}
      LINKDROP_HIDE_FOOTER: ${LINKDROP_HIDE_FOOTER}
      LINKDROP_HIDE_HEADER: ${LINKDROP_HIDE_HEADER}
      LINKDROP_HIDE_LOGO: ${LINKDROP_HIDE_LOGO}
      LINKDROP_NO_LISTING: ${LINKDROP_NO_LISTING}
      LINKDROP_HIGHLIGHTSYNTAX: ${LINKDROP_HIGHLIGHTSYNTAX}
      LINKDROP_BIND: ${LINKDROP_BIND}
      LINKDROP_PRIVATE: ${LINKDROP_PRIVATE}
      LINKDROP_PURE_HTML: ${LINKDROP_PURE_HTML}
      LINKDROP_DATA_DIR: ${LINKDROP_DATA_DIR}
      LINKDROP_JSON_DB: ${LINKDROP_JSON_DB}
      LINKDROP_PUBLIC_PATH: ${LINKDROP_PUBLIC_PATH}
      LINKDROP_SHORT_PATH: ${LINKDROP_SHORT_PATH}
      LINKDROP_READONLY: ${LINKDROP_READONLY}
      LINKDROP_UPLOADER_PASSWORD: ${LINKDROP_UPLOADER_PASSWORD}
      LINKDROP_SHOW_READ_STATS: ${LINKDROP_SHOW_READ_STATS}
      LINKDROP_TITLE: ${LINKDROP_TITLE}
      LINKDROP_THREADS: ${LINKDROP_THREADS}
      LINKDROP_GC_DAYS: ${LINKDROP_GC_DAYS}
      LINKDROP_ENABLE_BURN_AFTER: ${LINKDROP_ENABLE_BURN_AFTER}
      LINKDROP_DEFAULT_BURN_AFTER: ${LINKDROP_DEFAULT_BURN_AFTER}
      LINKDROP_WIDE: ${LINKDROP_WIDE}
      LINKDROP_QR: ${LINKDROP_QR}
      LINKDROP_ETERNAL_PASTA: ${LINKDROP_ETERNAL_PASTA}
      LINKDROP_ENABLE_READONLY: ${LINKDROP_ENABLE_READONLY}
      LINKDROP_DEFAULT_EXPIRY: ${LINKDROP_DEFAULT_EXPIRY}
      LINKDROP_NO_FILE_UPLOAD: ${LINKDROP_NO_FILE_UPLOAD}
      LINKDROP_CUSTOM_CSS: ${LINKDROP_CUSTOM_CSS}
      LINKDROP_HASH_IDS: ${LINKDROP_HASH_IDS}
      LINKDROP_ENCRYPTION_CLIENT_SIDE: ${LINKDROP_ENCRYPTION_CLIENT_SIDE}
      LINKDROP_ENCRYPTION_SERVER_SIDE: ${LINKDROP_ENCRYPTION_SERVER_SIDE}
      LINKDROP_DEFAULT_PRIVACY: ${LINKDROP_DEFAULT_PRIVACY}
      LINKDROP_MAX_FILE_SIZE_ENCRYPTED_MB: ${LINKDROP_MAX_FILE_SIZE_ENCRYPTED_MB}
      LINKDROP_MAX_FILE_SIZE_UNENCRYPTED_MB: ${LINKDROP_MAX_FILE_SIZE_UNENCRYPTED_MB}
      LINKDROP_DISABLE_UPDATE_CHECKING: ${LINKDROP_DISABLE_UPDATE_CHECKING}
      LINKDROP_DISABLE_TELEMETRY: ${LINKDROP_DISABLE_TELEMETRY}
      LINKDROP_LIST_SERVER: ${LINKDROP_LIST_SERVER}
